version: '3'
services:
  phoenix:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - SECRET_KEY_BASE=${SECRET_KEY_BASE}
     - CLIENT_APP_ORIGIN=${CLIENT_APP_ORIGIN}
    tty: true
    stdin_open: true
    ports:
      - "4000:4000"
  react:
    build:
      context: ./pictionary-app
      dockerfile: Dockerfile
    environment:
     - REACT_APP_SITE_URL=${CLIENT_APP_ORIGIN}
     - REACT_APP_HOST_URL=${API_HOST}
    volumes:
      - node-modules:/app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - phoenix
volumes:
  node-modules:
