// == Reducer actions ==

// settings:
export const TOGGLE_SOUND = 'TOGGLE_SOUND';
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE';
export const ADD_ALERT = 'ADD_ALERT';
export const CLEAR_ALERT = 'CLEAR_ALERT';
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const SAVE_SOCKET_OBJECT = 'SAVE_SOCKET_OBJECT';
export const SAVE_GAME_CHANNEL = 'SAVE_GAME_CHANNEL';
export const SAVE_GAME_TO_JOIN_ID = 'SAVE_GAME_TO_JOIN_ID';
export const CLEAR_SOCKET = 'CLEAR_SOCKET';

// userinfo:
export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const LOAD_SESSION = 'LOAD_SESSION';

// game:
export const SAVE_GAME = 'SAVE_GAME';
export const FAILED_SAVE_GAME = 'FAILED_SAVE_GAME';
export const UPDATE_GAME_STATE = 'UPDATE_GAME_STATE';
export const UPDATE_GAME_PLAYERS = 'UPDATE_GAME_PLAYERS';
export const ADMIN_UPDATED = 'ADMIN_UPDATED';
export const REMOVE_PLAYER = 'REMOVE_PLAYER';

// == Saga Actions ==
export const HANDLE_CREATE_USER_SESSION = 'HANDLE_CREATE_USER_SESSION';
export const HANDLE_RESTORE_SESSION = 'HANDLE_RESTORE_SESSION';
export const HANDLE_CREATE_GAME_SESSION = 'HANDLE_CREATE_GAME_SESSION';
export const HANDLE_SAVE_GAME = 'HANDLE_SAVE_GAME';
export const HANDLE_UPDATE_GAME = 'HANDLE_UPDATE_GAME';
export const HANDLE_INIT_SOCKET = 'HANDLE_INIT_SOCKET';
export const HANDLE_INIT_GAME_CHANNEL = 'HANDLE_INIT_GAME_CHANNEL';
export const HANDLE_CREATE_AND_ENTER_GAME_SESSION = 'HANDLE_CREATE_AND_ENTER_GAME_SESSION';
export const HANDLE_JOIN_EXISTING_GAME_SESSION = 'HANDLE_JOIN_EXISTING_GAME_SESSION';
export const HANDLE_CREATE_GAME_FLOW = 'HANDLE_CREATE_GAME_FLOW';
export const HANDLE_JOIN_GAME_FLOW = 'HANDLE_JOIN_GAME_FLOW';
export const HANDLE_GET_GAME_DATA = 'HANDLE_GET_GAME_DATA';
export const HANDLE_GAME_JOIN_SUCCESS = 'HANDLE_GAME_JOIN_SUCCESS';
export const HANDLE_GAME_JOIN_FAIL = 'HANDLE_GAME_JOIN_FAIL';
export const HANDLE_UPDATE_ADMIN = 'HANDLE_UPDATE_ADMIN';
export const HANDLE_KICK_PLAYER = 'HANDLE_KICK_PLAYER';
export const HANDLE_PLAYER_KICKED = 'HANDLE_PLAYER_KICKED';
export const HANDLE_ADMIN_UPDATED = 'HANDLE_ADMIN_UPDATED';
